location                         = "northeurope"
resource_group_name              = "rg-vri-prod"
storage_account_name             = "savriprod"
storage_account_tier             = "Standard"
storage_account_replication_type = "GRS"
container_name                   = "appdata-prod"
environment                      = "prod"
