location                         = "northeurope"
resource_group_name              = "rg-vri-dev"
storage_account_name             = "savridev"
storage_account_tier             = "Standard"
storage_account_replication_type = "LRS"
container_name                   = "appdata-dev"
environment                      = "dev"
